### ISSUE TITLE
Dropdown menus don't work

### ISSUE THREAD

**Issue by hayatoc** [nicekiwi/southern-eastercamp#33] opened 2014-02-09 07:25 UTC
Dropdown menus  don't... "drop down"

Windows: 
Doesn't work - Chrome, Firefox, Opera, IE

Fedora:
Doesn't work - Chrome, Firefox

![image](https://f.cloud.github.com/assets/640597/2119304/493f3d72-915b-11e3-8b4c-21285846ceb3.png)

**Comment by nicekiwi** [comment] 2014-02-09 07:27
Duplicate of #14

**Closed as completed by nicekiwi** 2014-02-09 07:27 UTC
Labels: duplicate
