### ISSUE TITLE
Drop Down Menus?

### ISSUE THREAD

**Issue by migrif** [nicekiwi/southern-eastercamp#15] opened 2014-02-09 06:48 UTC
There are drop down arrows next to Information & FAQ, but they do nothing.

(Also, site looks nice)

![screen shot 2014-02-09 at 7 46 52 pm](https://f.cloud.github.com/assets/5118567/2119249/072aa5c0-9156-11e3-80ea-e37dad805e0b.jpg)

**Comment by nicekiwi** [comment] 2014-02-09 06:51
Duplicate of #14

**Closed as completed by nicekiwi** 2014-02-09 06:51 UTC
Labels: duplicate
